### ISSUE TITLE
Screen sharing does not work on actual phone like oneplus . Suprisingly working through emulator

### ISSUE THREAD

**Issue by bjprogrammer** [voxeet/voxeet-uxkit-android#13]
2020-10-20 22:17:40.648 31710-1860/com.voxeet.sdk.sample E/org.webrtc.Logging: HardwareVideoEncoder: deliverOutput failed
2020-10-20 22:17:40.648 31710-1860/com.voxeet.sdk.sample E/org.webrtc.Logging: HardwareVideoEncoder: java.lang.IllegalStateException
2020-10-20 22:17:40.648 31710-1860/com.voxeet.sdk.sample E/org.webrtc.Logging: HardwareVideoEncoder: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2823)
        at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
        at org.webrtc.HardwareVideoEncoder.deliverEncodedImage(HardwareVideoEncoder.java:489)
        at org.webrtc.HardwareVideoEncoder$1.run(HardwareVideoEncoder.java:477)

**Comment by FabienLavocat** [comment]
What Android API are you targeting?

**Comment by bjprogrammer** [comment]
I have already resolved this. Issue was with some very high resolution phones.I had to pass screen size information before calling RightToScreenShare method.

        DisplayMetrics dm = getResources().getDisplayMetrics();
        VoxeetSDK.screenShare().setScreenSizeInformation(new Point(dm.heightPixels,dm.widthPixels));
        VoxeetSDK.screenShare().consumeRightsToScreenShare();

**Comment by thakurs9dp** [comment]
App crash when i start screen share,  errror - uxkit.implementation.overlays.OverlayState.ordinal()' on a null object reference
