### ISSUE TITLE
Crash on Android devices

### ISSUE THREAD

**Issue by ShengjieGeng** [voxeet/voxeet-uxkit-android#24]
Hello,
Some error happened after our APP minifyEnabled.
So how can I add the proguard roles?
Thanks.

**Comment by codlab** [comment]
Please follow the proguard/minify snippet from https://github.com/voxeet/voxeet-sdk-android#proguard-integration

It has also been updated to reflect a typo in the `dolby.voice` pragma

**Comment by ShengjieGeng** [comment]
Sorry to bother, but there is a NoSuchMethodError when the project minifyEnabled
```
2021-09-06 09:48:37.639 3116-3116/com.semcorel.edge E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.semcorel.edge, PID: 3116
    java.lang.NoSuchMethodError: No virtual method I1I()Ljava/lang/String; in class Ljava/lang/Class; or its super classes (declaration of 'java.lang.Class' appears in /system/framework/core-oj.jar)
        at com.voxeet.sdk.manifests.AbstractManifestComponentProvider.attachInfo(AbstractManifestComponentProvider.java:27)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
Please do me a favor if you are available.
Thank you very much!

**Comment by ShengjieGeng** [comment]
By the way, the proguard-rules as follow:
```
# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile
-ignorewarnings
#所有的bean都保留，因为要gson format
-keep class com.semcorel.edge.bean.** { *; }
-keep class com.semcorel.edge.vo.** { *; }
-keep class com.semcorel.edge.entity.** { *; }
-keep class com.semcorel.edge.common.** { *; }
-keep class com.semcorel.edge.msgevent.** { *; }
-keep class androidx.sqlite.** { *; }
-keep class androidx.sqlite.** { *; }
-keep,includedescriptorclasses class net.sqlcipher.** { *; }
-keep,includedescriptorclasses interface net.sqlcipher.** { *; }
# 避免混淆泛型, 这在JSON实体映射时非常重要
#-keepattributes Signature
# 抛出异常时保留代码行号
-keepattributes SourceFile,LineNumberTable
#不进行优化，建议使用此选项，
-dontoptimize
 # 不进行预校验,Android不需要,可加快混淆速度。
-dontpreverify

# -----------------------------------变态混淆-----------------------------------------
# 混淆的压缩比例，0-7
-optimizationpasses 5
# 指定不去忽略非公共的库的类的成员
-dontskipnonpubliclibraryclassmembers
# 指定混淆是采用的算法
-optimizations !code/simplification/arithmetic,!code/simplification/cast,!field/*,!class/merging/*
# 指定外部模糊字典 proguard-chinese.txt 改为混淆文件名，下同
-obfuscationdictionary proguard-1il.txt
# 指定class模糊字典
-classobfuscationdictionary proguard-1il.txt
# 指定package模糊字典
-packageobfuscationdictionary proguard-1il.txt
#---------------------------------------------变态混淆------------------------------------
-keep class com.google.gson.examples.models.** { *; }
-keep interface com.google.gson.examples.models.** { *; }
-keep class com.google.gson.examples.upgrade.internal.VersionInfo {*;}

#---------------------okhttp---------------------
# JSR 305 annotations are for embedding nullability information.
-dontwarn javax.annotation.**

# A resource is loaded with a relative path so the package of this class must be preserved.
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

# Animal Sniffer compileOnly dependency to ensure APIs are compatible with older versions of Java.
-dontwarn org.codehaus.mojo.animal_sniffer.*

# OkHttp platform used only on JVM and when Conscrypt dependency is available.
-dontwarn okhttp3.internal.platform.ConscryptPlatform
#--------------retrofit
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keep public class * extends retrofit2.Converter {*;}
#-------------eventbus--------------------------------------
-keepattributes *Annotation*
-keepclassmembers class * {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
# Only required if you use AsyncExecutor
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}
#-----------------------------------------glide-------------------------------------
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
# -----------------web view------------------
-keepclassmembers class fqcn.of.javascript.interface.for.Webview {
   public *;
}
-keepclassmembers class * extends android.webkit.WebViewClient {
    public void *(android.webkit.WebView, java.lang.String, android.graphics.Bitmap);
    public boolean *(android.webkit.WebView, java.lang.String);
}
-keepclassmembers class * extends android.webkit.WebViewClient {
    public void *(android.webkit.WebView, jav.lang.String);
}
#--------------green dao
-keepclassmembers class * extends org.greenrobot.greendao.AbstractDao {
public static java.lang.String TABLENAME;
}
-keep class **$Properties { *; }

# If you DO use SQLCipher:
-keep class org.greenrobot.greendao.database.SqlCipherEncryptedHelper { *; }

#gao de map
-keep class com.amap.api.maps2d.**{*;}
-keep class com.amap.api.mapcore2d.**{*;}

-keepclasseswithmembers class * {
    ... *JNI*(...);
}
-keepclasseswithmembernames class * {
    ... *JRI*(...);
}
-keep class **JNI* {*;}

#-------------------voxeet-----------------
-keep class com.voxeet.** { *; }
-keep interface com.voxeet.** { *; }

-keep class org.webrtc.** { *; }
-keep interface org.webrtc.** { *; }

-keep class com.dolby.voice.** { *; }
-keep interface com.dolby.voice.** { *; }

-keep public class pl.droidsonroids.gif.GifIOException{<init>(int);}
-keep class pl.droidsonroids.gif.GifInfoHandle{<init>(long,int,int,int);}
```

**Comment by codlab** [comment]
Since the error is from *I1I()Ljava/lang/String; in class Ljava/lang/Class;*

Try using -keep class java.lang.Class { *; }

**Comment by ShengjieGeng** [comment]
> Since the error is from _I1I()Ljava/lang/String; in class Ljava/lang/Class;_
> 
> Try using -keep class java.lang.Class { *; }

Yeah，you are right.

**Comment by ShengjieGeng** [comment]
> Since the error is from _I1I()Ljava/lang/String; in class Ljava/lang/Class;_
> 
> Try using -keep class java.lang.Class { *; }

Yeah, you are right.
But there somehow are other errors like : in class Ljava/lang/String; in class Ljava/io/File, etc.
```
2021-09-06 10:14:56.768 3713-3713/com.semcorel.edge E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.semcorel.edge, PID: 3713
    java.lang.NoSuchMethodError: No virtual method 丨il()Ljava/io/File; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)
        at androidx.core.content.FileProvider$ILil.IL1Iii(FileProvider.java:715)
        at androidx.core.content.FileProvider.ILil(FileProvider.java:653)
        at androidx.core.content.FileProvider.IL1Iii(FileProvider.java:579)
        at androidx.core.content.FileProvider.attachInfo(FileProvider.java:392)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
To be honest, I don't know the why. Does my proguard-rules are written incorrectly?
I'll appreciate if you have any idea,

**Comment by codlab** [comment]
Those errors does not seem to be related with our SDK but something which could be related to multidex

however, you should a rules for :

java.lang.**
java.io.**

Generally, every time after, when you get `java.lang.NoSuchMethodError: No virtual method XX in class Lsome/package/Class;`
It means you need a rule for some.package.Class - when some.package is a package holding multiple classes like above java.lang, you can safely use some.package.**

**Comment by ShengjieGeng** [comment]
I'll give it a try. 
Thank you very much!
