### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by ShengjieGeng** [voxeet/voxeet-uxkit-android#35]
Sorry, But I have no any idea why the exception happened when building a release apk(debug apk will not see this exception).
If you have any clue, please let me know!
Thank you very much!
```
2021-11-04 15:35:59.764 2751-2751/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.semcorel.coco.tablet, PID: 2751
    java.lang.RuntimeException: Unable to create application com.semcorel.coco.application.MyApplication: java.lang.IllegalArgumentException: Illegal URL: Target
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5907)
        at android.app.ActivityThread.access$1200(ActivityThread.java:206)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
     Caused by: java.lang.IllegalArgumentException: Illegal URL: Target
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:454)
        at com.voxeet.sdk.services.VoxeetHttp.createClientRetrofits(VoxeetHttp.java:233)
        at com.voxeet.sdk.services.VoxeetHttp.initRetrofit(VoxeetHttp.java:263)
        at com.voxeet.sdk.services.VoxeetHttp.init(VoxeetHttp.java:112)
        at com.voxeet.VoxeetSDK.internalInitialize(VoxeetSDK.java:219)
        at com.voxeet.VoxeetSDK.initialize(VoxeetSDK.java:143)
        at com.semcorel.coco.common.service.ConferenceService.registerApplication(ConferenceService.java:113)
        at com.semcorel.coco.common.service.ConferenceService.initialize(ConferenceService.java:37)
        at com.semcorel.coco.common.service.ServiceController.initialize(ServiceController.java:40)
        at com.semcorel.coco.common.controller.Controller.initialize(Controller.java:30)
        at com.semcorel.coco.application.MainApplication.onCreate(MainApplication.java:89)
        at com.semcorel.coco.application.MyApplication.onCreate(MyApplication.java:39)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)

```

**Comment by ShengjieGeng** [comment]
by the way, my gradle as below:
```
 buildTypes {
        debug {
            signingConfig signingConfigs.release
        }

        release {
            lintOptions {
                checkReleaseBuilds false
                abortOnError false
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        buildTypes.each {
            it.buildConfigField "String", "CONSUMER_KEY", "\"" + project.properties["CONSUMER_KEY"]+"\""
            it.buildConfigField "String", "CONSUMER_SECRET", "\"" + project.properties["CONSUMER_SECRET"]+"\""
        }
    }
```
